### ISSUE TITLE
Проверка при отправке трансферов.

### ISSUE THREAD

**Issue by raywave** [cursedseal/VCoinX#1]
Написать руководство по отправке трансферов, либо добавить дополнительные проверки.

Запятая при отправке, кавычки при проверке на согласие.

**Comment by citramone1** [comment]
Привет, спасибо за софт. а что случилось то?

**Comment by djimboy** [comment]
Как сделать чтобы бот добывал коины в группу?

**Comment by JoshOOOOWAH** [comment]
Руководства будет достаточно, кому надо, прочтут трижды
