### ISSUE TITLE
Транфер

### ISSUE THREAD

**Issue by banysk** [cursedseal/VCoinX#10]
Люди добрые, кто может объяснить, как сделать, чтобы деньги автоматом переводились на аккаунт? Опишите, кому не сложно, пожалуйста

**Comment by raywave** [comment]
Привет, довольно часто задаваемый вопрос.

В параметрах запуска бота нужно добавить три аргумента: -tsum, -to, -ti.

В итоге получится что-то вроде `-tsum 10000 -to 12345678 -ti 300`, что будет значить, что переводиться будут 10.000 коинов пользователю с айди 12345678 с интервалом в 300 секунд (5 минут).

Установить параметры запуска можно в файле `2. launch` с помощью редактирования его через любой текстовый редактор.

![image](https://user-images.githubusercontent.com/41350030/55557948-b548ce80-56f3-11e9-8f94-98ac13c92f84.png)
