### ISSUE TITLE
Не отправляются коины

### ISSUE THREAD

**Issue by apepenkov** [cursedseal/VCoinX#101]
![изображение](https://user-images.githubusercontent.com/39992738/55672828-5a0c0d00-58a8-11e9-8ae3-7a2aeb64a563.png)

отправляется при запуске пару раз, потом перестает.
node index.js -t ******* -to 330464853 -ti 5 -tperc 90 -smartBuy

**Comment by raywave** [comment]
посмотрю по этому поводу.

**Comment by apepenkov** [comment]
Ок. Node js 8.15.1, os ubuntu

**Comment by raywave** [comment]
Вероятно, ошибка API, ничем помочь не могу.
