### ISSUE TITLE
Не входит в аккаунт

### ISSUE THREAD

**Issue by coldfeudal** [cursedseal/VCoinX#105]
При попытке запустить бота, выдает ошибку. Токены менять пробовал
![image](https://user-images.githubusercontent.com/27438739/55673347-bc1c4080-58af-11e9-9c4d-a7bba9ed3e46.png)

**Comment by ghost** [comment]
Тоже появилось сейчас

**Comment by olezhkoff** [comment]
токены стали динамические

**Comment by Slivondiy** [comment]
Какие то промокоды Деливери добавили vkcoin

**Comment by raywave** [comment]
не юзать legacy версию?
