### ISSUE TITLE
Не запускается ( решено)

### ISSUE THREAD

**Issue by vander00** [cursedseal/VCoinX#107]
Не запускается. Токен менял уже 3 раза.
![Снимок](https://user-images.githubusercontent.com/49349382/55673952-60ee4c00-58b7-11e9-8939-936bcdc1df81.PNG)

**Comment by vander00** [comment]
Я уже исправил. Во всем виновата тупость. Но тут следующая проблема, уже не из за меня
![Снимок](https://user-images.githubusercontent.com/49349382/55674035-ccd0b480-58b7-11e9-8f6a-3253ce95093e.PNG)

**Comment by vander00** [comment]
Я решил проблему.

**Comment by YanLiudchyk** [comment]
> Я решил проблему.

Как?

**Comment by Snow4DV** [comment]
Такая же проблема. Как решил?)

**Comment by CRISPPO** [comment]
Как решить эту проблему?

**Comment by Snow4DV** [comment]
> Как решить эту проблему?

Смотри недавние issue, мы там решили эту проблему и там же есть фикс архивом
