### ISSUE TITLE
package.json ошибка

### ISSUE THREAD

**Issue by andreyazimoov** [cursedseal/VCoinX#108]
pm ERR! file /root/16/package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token
npm ERR! JSON.parse  in JSON at position 42 while parsing '{
npm ERR! JSON.parse   "name": "vcoinx",
npm ERR! JSON.parse   "version": "1.3.'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

**Comment by GhostZ9817** [comment]
Update package.json	8 minutes ago

**Comment by ghost** [comment]
Пофиксили уже

**Comment by raywave** [comment]
давно фикс
