### ISSUE TITLE
Автоплатеж переводит койны по 2 раза

### ISSUE THREAD

**Issue by EgrorBs** [cursedseal/VCoinX#110]
![image](https://user-images.githubusercontent.com/44816767/55674149-503ed580-58b9-11e9-8861-0d8a27f807e3.png)

Это фиксится примерно так) (я тестил на прошлой (или уже позапрошлой...) версии)
![image](https://user-images.githubusercontent.com/44816767/55674183-a01d9c80-58b9-11e9-9e48-443bd1d037a7.png)

**Comment by raywave** [comment]
фикс будет.
