### ISSUE TITLE
Не всегда правильно воспринимаются параметры (с предложением фикса)

### ISSUE THREAD

**Issue by EgrorBs** [cursedseal/VCoinX#112]
Закономерности не нашел, но если привести строки 556-638 к виду строк 511-551 (и вырезать 552-554) то все работает шикарно (пример фикса с прошлой(или позапрошлой...) версии ниже)

### Prev:
![image](https://user-images.githubusercontent.com/44816767/55674272-225a9080-58bb-11e9-8e70-f7fc6e6645b4.png)
### Code:
https://pastebin.com/990JUNhD

_P.S. pastebin ибо тут криво код вставлялся, да и не красиво простыни такие выкладывать :)_

**Comment by raywave** [comment]
тесты были?

**Comment by raywave** [comment]
если были тесты - добавлю

**Comment by raywave** [comment]
я еблан, в некст обнове - фикс
