### ISSUE TITLE
Не запускается, Unexpected token

### ISSUE THREAD

**Issue by Snow4DV** [cursedseal/VCoinX#113]
Вечер добрый) Бот не хочет стартовать, машина на линуксе. 

Вся инфа: 
1) npm -v 5.3.0
2) Конфигурационный файл: http://prntscr.com/n8fhup

При запуске выбивает вот это вот: http://prntscr.com/n8fi27

Что делать?) Как заставить бота стартануть?)

**Comment by therain7** [comment]
можно попробовать полностью избавиться от модуля open и куска кода, содержащего его

**Comment by therain7** [comment]
а именно в index.js удали полностью 2 и 233 строчки, также в package.json и package-lock.json убери все упоминания этого модуля(в package.json удали 9 строку, в package-lock.json удали все с 364 по 371 строку включительно )

**Comment by DpO4uLa** [comment]
качни последнюю версию бота.

**Comment by Snow4DV** [comment]
Благодарю! Майнинг пошел)  Для тех, кто столкнется с такой же проблемой, архив с исправленными файлами, его в корень распаковать:

[FixUnexpectedToken.zip](https://github.com/cursedseal/VCoinX/files/3050858/FixUnexpectedToken.zip)

**Comment by Snow4DV** [comment]
> качни последнюю версию бота.

Версия последняя,  гитал 15 минут назад.
