### ISSUE TITLE
Проблемы с аргументами

### ISSUE THREAD

**Issue by DpO4uLa** [cursedseal/VCoinX#114]
Не реагирует при запуске с linux на аргументы -tsum и -ti. С windows не пробовал

**Comment by Dpo4uLa** [comment]
код, которым стартую:
node index.js -t мой_токен -to 256366873 -ti 3 -tsum 10000,000

**Comment by DpO4uLa** [comment]
node index.js -t мой_токен -to мой_ид -ti 3 -tsum 10000,000

**Comment by therain7** [comment]
в tsum попробуй убрать запятую и нули:
node index.js -t мой_токен -to мой_ид -ti 3 -tsum 10000

**Comment by DpO4uLa** [comment]
не пашет

**Comment by DpO4uLa** [comment]
в чат выводит, что только токен и авто перевод на id установлен, не более

**Comment by therain7** [comment]
попробовал сам. у меня вообще сумма перевода бралась из аргумента ti и т.д. вообщем думаю эта проблема относится к https://github.com/cursedseal/VCoinX/issues/112
