### ISSUE TITLE
tperc - Сумма переводится дважды

### ISSUE THREAD

**Issue by Homosanians** [cursedseal/VCoinX#117]
![image](https://user-images.githubusercontent.com/35880220/55674648-fd1c5100-58bf-11e9-92a9-9ae1eb2419a9.png)

Нужна сумма переводиться дважды при использовании tperc

tperc 3

debug:
updatesInterval 60
updatesLastTime 0
xRestart true
autobuy false
smartbuy false
transferScore 2592
transferInterval 1800
transferLastTime 1554580740

**Comment by therain7** [comment]
https://github.com/cursedseal/VCoinX/pull/111 - скоро исправит

**Comment by raywave** [comment]
фикс будет
