### ISSUE TITLE
куча багов

### ISSUE THREAD

**Issue by svyanov** [cursedseal/VCoinX#122]
какая то дичь с авто переводами
правильно указал id и сумму и время в 1 сек
ниче не переводит

умная закупка вообще не понимаю как работает
у бота 500 000, 000 на счету, но при этом 0 в сек, бот ниче не покупает (

**Comment by LifeViwer** [comment]
Ты её для начало включи! По дефолту всё отключено!

**Comment by raywave** [comment]
1. настиаивать научись.
2. значит нужное улучшение недоступно для покупки
