### ISSUE TITLE
Трей

### ISSUE THREAD

**Issue by Sperma4ez** [cursedseal/VCoinX#127]
Добрый день, хотелось бы увидеть функцию укрывания программы в трей.

**Comment by Fomikus** [comment]
Win+TAB = PROFFIT!

**Comment by Sperma4ez** [comment]
Ну как бы Ваш "proffit" - переключение между запущенными программами, а не скрытие программы в трей.

**Comment by raywave** [comment]
потом мб введу, годно.

**Comment by raywave** [comment]
изменил свое мнение, не годно.
