### ISSUE TITLE
Win 10 Ошибки

### ISSUE THREAD

**Issue by VoQZHD** [cursedseal/VCoinX#128]
![image](https://user-images.githubusercontent.com/45748775/55680453-86249e00-593b-11e9-87d7-68a35c1f7e35.png)

**Comment by Allespro** [comment]
Из за чего такие ошибки происходят не всегда понятно, можешь не ждать ответа

**Comment by Fomikus** [comment]
1) Перекачай
2) Еще раз получи токен и поменяй в config.js
3) PROFFIT

**Comment by Ars1k** [comment]
> 1. Перекачай
> 2. Еще раз получи токен и поменяй в config.js
> 3. PROFFIT

А можно в config,js сразу несколько токенов забить и чтобы несколько акков открылись?

**Comment by mulfyx** [comment]
> > 1. Перекачай
> > 2. Еще раз получи токен и поменяй в config.js
> > 3. PROFFIT
> 
> А можно в config,js сразу несколько токенов забить и чтобы несколько акков открылись?

нельзя, но я сделал свою реализацию...

**Comment by VoQZHD** [comment]
> > > 1. Перекачай
> > > 2. Еще раз получи токен и поменяй в config.js
> > > 3. PROFFIT
> > 
> > 
> > А можно в config,js сразу несколько токенов забить и чтобы несколько акков открылись?
> 
> нельзя, но я сделал свою реализацию...
