### ISSUE TITLE
Фарминг от группы

### ISSUE THREAD

**Issue by ghost** [cursedseal/VCoinX#13]
нигде не нашел, как фармить от группы, можно ли так сделать?

**Comment by citramone1** [comment]
Как я понял баланс группы это твой баланс

**Comment by ghost** [comment]
Нет, есть отдельная кнопка в группе, которую при входе в майнинг нужно нажимать, все что намайнено при входе с этой кнопки суммируется (с другими пользователями)

**Comment by raywave** [comment]
Привет, если разбираешься - то при получении ссылки можно указать айди группы, функцию как таковую я еще не реализовал.

**Comment by ghost** [comment]
Ок спс
