### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by Sacmi** [cursedseal/VCoinX#133]
А не хочешь собирать бота в один exe-шник? Ведь у этого есть два плюса. Во первых, всяким челикам не придется ебаться с установкой nodejs и пакетов. А во вторых, они не смогут убрать твою рекламу. Как мне кажется, мало кто захочет копаться в коде и пересобирать exe-шник.

Кста, могу помочь с реализацией этой идеи

**Comment by raywave** [comment]
Не хочу пересобирать в один `exe`-шник, не очень нравится эта идея.

**Comment by Sacmi** [comment]
А чем она тебе не нравится? Собирается одной командой и времени занимает 3-5 секунд. Да и в коде трогать ничего не надо
