### ISSUE TITLE
tperc, как параметр запуска

### ISSUE THREAD

**Issue by cherrynik** [cursedseal/VCoinX#137]
Ребятушки, при разработке, вы тут упустили, поэтому я тут вам код уж написал:
`case '-tperc': { if (dTest.length >= 1 && dTest.length < 10) { transferPercent = parseInt(dTest); con("Установлен интервал для автоматического перевода: " + transferPercent + " секунд."); argn++; } break; }`

В argument parsing, с 525 строки

**Comment by TheDeaX-Lab** [comment]
@ighosta9  https://github.com/cursedseal/VCoinX/pull/135 потом сказали обновят. Тема закрыта

**Comment by cherrynik** [comment]
@TerryChan2003, делов пару минут, я только что это сделал, у меня эта фигня работает терь, чё на потом-то тянуть, пхпхпх.

**Comment by TheDeaX-Lab** [comment]
@ighosta9 ну да я согласен, просто делать форк для себя самого лучше будет

**Comment by Slivondiy** [comment]
> Ребятушки, при разработке, вы тут упустили, поэтому я тут вам код уж написал:
> `case '-tperc': { if (dTest.length >= 1 && dTest.length < 10) { transferPercent = parseInt(dTest); con("Установлен интервал для автоматического перевода: " + transferPercent + " секунд."); argn++; } break; }`
> 
> В argument parsing, с 525 строки

Куда этот отрывок сувать?

**Comment by cherrynik** [comment]
@Slivondiy между любым кейсом в свитче. С 525 строки ищи. Index.js
