### ISSUE TITLE
Прокси

### ISSUE THREAD

**Issue by EgrorBs** [cursedseal/VCoinX#138]
Предлагаю добавить возможность пускать соединения через прокси-сервер

(Что-то типа такого https://github.com/TooTallNate/node-https-proxy-agent#ws-websocket-connection-example )

**Comment by raywave** [comment]
позднее добавлю с указанием проксей через аргументы запуска наверн

**Comment by Allespro** [comment]
А перед командой запуска писать http-proxy="127.0.0.1:8080"? Намример для тор соединения.

**Comment by TheDeaX-Lab** [comment]
@Allespro всё скоро потом узнаем. Может проще сделают. Нужен функционал ещё чтобы оставалось хоть какое то количество коинов, чтобы мне потом раздачи устраивать

**Comment by Allespro** [comment]
> @Allespro всё скоро потом узнаем. Может проще сделают. Нужен функционал ещё чтобы оставалось хоть какое то количество коинов, чтобы мне потом раздачи устраивать

Так вроде можно использовать проценты, в README написано. Коины будут оставаться)

**Comment by TheDeaX-Lab** [comment]
@Aliespro не понял суть) проценты мне никак не помогают, к примеру я хочу сохранить миллион коинов, а остальное пусть раскидывает и прокачивает, а там уже проценты меняются

**Comment by raywave** [comment]
возможно, что очень скоро. . .
