### ISSUE TITLE
Подтверждение пользователя при переводе баланса и авто-переводе

### ISSUE THREAD

**Issue by salwador** [cursedseal/VCoinX#139]
Вполне можно получать имя & фамилию юзера по его ID, для подтверждения перевода, когда ожидается ввод "yes". Обезопасит фаршмаков от ошибочных транзакций.

Так же по команде "to" тоже можно приклеить аналогичное подтверждение. Не особо полезно, но why not? Мир полон идиотов.

**Comment by Slivondiy** [comment]
+, вот это ТЕМА))

**Comment by raywave** [comment]
будет.

**Comment by raywave** [comment]
+ возможность юзать буквенный айди.

**Comment by raywave** [comment]
спасибо за идею кстати. <3

**Comment by raywave** [comment]
в to добавлять не буду
