### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by kageminori** [cursedseal/VCoinX#14]
По кд такие ошибки.
![image](https://user-images.githubusercontent.com/40120252/55571985-509b6d00-570f-11e9-9f7c-c5c3d2ce53f7.png)

**Comment by kageminori** [comment]
Что сделать, что бы заработало?
 xD

**Comment by DiSonDS** [comment]
![image](https://user-images.githubusercontent.com/10602386/55575157-e71f5c80-5716-11e9-9fd5-0ab1815723ce.png)
 Жиза

**Comment by raywave** [comment]
Ждать, пишите в ТП - https://vk.com/vcoinx
