### ISSUE TITLE
Структура кода.

### ISSUE THREAD

**Issue by de-don** [cursedseal/VCoinX#141]
Разбей файл `index.js` на несколько файлов, сделай небольшие описания.
А то смотреть диффы километровые не очень удобно :)

Все же у тебя опенсорс бот, и многие смотрят код.

**Comment by Slivondiy** [comment]
Ну тогда лучше сделать 2 отдельных скрипта, так как есть не опытные которым это не надо, им главное скачать и пользоваться программой)

**Comment by Fomikus** [comment]
Не так уж там и много строчек + функции с понятным названием

**Comment by raywave** [comment]
комментарии не люблю делать, ибо это описание к каждому шагу, так ничему не научиться, дать готовый код - пусть методом тыка ищут и понимают.
