### ISSUE TITLE
При указании tsum 0 или ti 0 некорректно работает автоперевод

### ISSUE THREAD

**Issue by EgrorBs** [cursedseal/VCoinX#142]
Ошибка BAD_ARGS
Для фикса нужно 
`if (transferTo && (transferCoins * 1e3 < score || transferCoins * 1e3 >= 9e9) && ((Math.floor(Date.now() / 1000) - transferLastTime) > transferInterval)) {`
заменить на 
`if (transferTo && transferCoins > 0 && transferInterval > 0 && ((Math.floor(Date.now() / 1000) - transferLastTime) > transferInterval)) {`

**Comment by raywave** [comment]
для чего вы вообще пытаетесь выставить некорректные аргументы, очевидно, что работать не будет.
