### ISSUE TITLE
Не очень умная авто покупка

### ISSUE THREAD

**Issue by Rasty96** [cursedseal/VCoinX#149]
При умной покупке лучше купить датацентр, стоит он в четверть дешевле и даст в 2 раза больше чем покупать квант пк но видимо бот думает иначе ))0
![image](https://user-images.githubusercontent.com/49373249/55687486-21d30000-5976-11e9-8f24-2246fc2fcae4.png)

**Comment by cbugerr** [comment]
та же проблема
суммирует неправильно

**Comment by raywave** [comment]
хз как фиксить
