### ISSUE TITLE
сокращение кол-ва уведомлений

### ISSUE THREAD

**Issue by DOmenza** [cursedseal/VCoinX#153]
Как сделать так , чтобы уведомления о моем месте и количестве коинов, приходили не раз в 2-3 секунды , а, допустим раз в минуту

**Comment by Olmae** [comment]
Вроде такого нет, но идея годная

**Comment by DOmenza** [comment]
а я о чем. Мы с другом сидели вырезали не нужный контент из индекса, дабы сократить расход оперативной памяти. Ну и начали искать в коде интервал. Так и не нашли...\

**Comment by raywave** [comment]
интервала нет мб? отображение сразу при получении
