### ISSUE TITLE
Ошибка в слове

### ISSUE THREAD

**Issue by SanHero** [cursedseal/VCoinX#154]
![фикс](https://user-images.githubusercontent.com/49374477/55688228-7c815180-59a0-11e9-9ee8-de077531e2e3.PNG)

перевод не удалАся

**Comment by Slivondiy** [comment]
Афигеть ошибка года, чтож теперь будет то?

**Comment by DOmenza** [comment]
ахах, чет даже внимание не обратил))

**Comment by Olmae** [comment]
Теперь закроют приложение, и посадят админов, прикольная ошибка
