### ISSUE TITLE
Работа в спящем режиме

### ISSUE THREAD

**Issue by sadbarash** [cursedseal/VCoinX#157]
Было бы ваще круто если бы прога работала когда комп в спящем режиме или в гибернации.

**Comment by egorprnn** [comment]
Вы понимаете что такое невозможно?

**Comment by TheDeaX-Lab** [comment]
@sadbarash ты понимаешь что ты поехавший), в спящем режиме ничего не работает и в гибернации тоже

**Comment by raywave** [comment]
ответ выше
