### ISSUE TITLE
Неправильная работа автозакупки

### ISSUE THREAD

**Issue by bar2104y** [cursedseal/VCoinX#158]
При включенной автозакупке скрипт копит денег больше чем надо. Так при стоимости Квантового компьютера в 200 коинов, скрипт копит 260, после чего производит покупку. Именно столько стоит следующий уровень.

Таким образом скрипт копит деньги, путая уровни цены: при стоимости первого 200, копит 260, из которых потом тратит только 200, затем при стоимости прокачки 260, копит 338, что составляет цену прокачки третьего уровня

**UPD**
Работает через раз. Судя по всему ошибка возникает только при первой автозакупке после запуска скрипта

**Comment by TheDeaX-Lab** [comment]
@bar2104y мне кажется раньше автопокупка была в разы адекватнее. Я учитываю версию 1.3.1

**Comment by raywave** [comment]
у меня все нормально.
