### ISSUE TITLE
Не находит аргументов при запуске

### ISSUE THREAD

**Issue by innomaxx** [cursedseal/VCoinX#16]
Последняя версия
git clone, npm i
![image](https://user-images.githubusercontent.com/40697586/55579236-711ff300-5720-11e9-987b-82d2ba9d562b.png)

**Comment by raywave** [comment]
хм, честно, не знаю в чем ошибка.

скорее всего в виртуальной машине.

**Comment by KoSHeroff** [comment]
![image](https://user-images.githubusercontent.com/49311737/55630019-b3e7d680-57c5-11e9-8fa7-f2e403d14048.png)

Не могу понять, в чём дело?

**Comment by Slivondiy** [comment]
**Скачал последнее обновление, пошли какие ошибки**
![Снимок](https://user-images.githubusercontent.com/49315027/55636708-1cd24d00-57cc-11e9-9996-293632d5e5db.JPG)

**Comment by can4ez** [comment]
`if(process.argv[argn] == '-autoBuy')` // -auto**B**uy
Измените на
`if(process.argv[argn] == '-autobuy')`

`if (process.argv[argn] == '-autoBuyItem')` // -auto**B**uy**I**tem
Изменить на
`if (process.argv[argn] == '-autobuyitem')`

`"-autoBuyItem"].includes` // -auto**B**uy**I**tem
Изменить на 
`"-autobuyitem"].includes`

В аргументах еще нет, сам по себе вроде работает, команда есть
`    if (process.argv[argn] == '-smartbuy') {
            smartBuy = !smartBuy;
            con("Умная покупка: " + (smartBuy ? "Включена" : "Отключена"));
            autoBuy = false;
            con("Автопокупка: " + (autoBuy ? "Включена" : "Отключена"));
        continue;
    }`

**Comment by tapakeht** [comment]
> `if(process.argv[argn] == '-autoBuy')` // -auto**B**uy
> Измените на
> `if(process.argv[argn] == '-autobuy')`
> 
> `if (process.argv[argn] == '-autoBuyItem')` // -auto**B**uy**I**tem
> Изменить на
> `if (process.argv[argn] == '-autobuyitem')`
> 
> `"-autoBuyItem"].includes` // -auto**B**uy**I**tem
> Изменить на
> `"-autobuyitem"].includes`
> 
> В аргументах еще нет, сам по себе вроде работает, команда есть
> ` if (process.argv[argn] == '-smartbuy') { smartBuy = !smartBuy; con("Умная покупка: " + (smartBuy ? "Включена" : "Отключена")); autoBuy = false; con("Автопокупка: " + (autoBuy ? "Включена" : "Отключена")); continue; }`

Можешь указать файлы и строки?

**Comment by tapakeht** [comment]
не выходит по твоему методу, заменил эти опечатки и итог тот же

**Comment by raywave** [comment]
фикс 1.3.0 вроде бы
