### ISSUE TITLE
Сохранение настроек

### ISSUE THREAD

**Issue by onloocker** [cursedseal/VCoinX#160]
Предлагаю ввести сохранение конфигурации бота в файл.
А также можно ввести профили для сохранения с возможностью переключаться между ними, т.е. для примера
Сохраняю первый профиль с настройками: smartbuy, деньги не переводить
Второй профиль с настройками: переводить N коинов каждые t секунд
Третий ещё с какие-нибудь настройками

**Comment by Fomikus** [comment]
Есть аргументы и запуск бота с ними, сложно сделать самому 2 батника?
![notepad++_F7WemvpNZq](https://user-images.githubusercontent.com/49315158/55727634-797b7500-5a23-11e9-8a99-39a5fdd9d5ec.png)

**Comment by onloocker** [comment]
Ты немного не понял или мне стоило дополнить: чтобы можно было менять конфигурации на горячую, т.е. не перезапуская бота

**Comment by onloocker** [comment]
По твоей логике тогда не нужны команды вовсе, а просто брать и перезапускать бота с аргументами

**Comment by Fomikus** [comment]
Во время работы можно отключить все что угодно, на то и есть команды

**Comment by raywave** [comment]
сохранений не будет
