### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Sperma4ez** [cursedseal/VCoinX#163]
![1](https://user-images.githubusercontent.com/49130022/55724732-b5f3a480-5a14-11e9-8cc7-91e815f0ba2d.jpg)

**Comment by Sperma4ez** [comment]
Приобретён*

**Comment by TheDeaX-Lab** [comment]
@Sperma4ez  всем пофиг)

**Comment by raywave** [comment]
пофикшу
