### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by imring** [cursedseal/VCoinX#166]
за место самой проблемы выводится объект.
![](https://media.discordapp.net/attachments/447759797400633377/564802978662580250/unknown.png)

**Comment by Fomikus** [comment]
Переделай токен (Еще раз получи его по ссылке из описания)

**Comment by imring** [comment]
> Переделай токен (Еще раз получи его по ссылке из описания)

все нормально с токеном. я вообще говорю про ошибку в js коде.

**Comment by raywave** [comment]
исправлю
