### ISSUE TITLE
Доделка бота

### ISSUE THREAD

**Issue by XzzetiX** [cursedseal/VCoinX#169]
Прошу вас сделать чтобы в команде to - указанию id можно было бы указывать id как с цифрами так и с буквами.
Т.к многие люди фармят на основу и не могут скидывать туда коины т.к в боте не указываются буквы, только цифры.

**Comment by daniorio** [comment]
Лол, вообще что-ли думать люди разучились?

**Comment by ghost** [comment]
> Лол, вообще что-ли думать люди разучились?

Нет, просто кто-то ленивый и не любит лишних телодвижений)

**Comment by Fomikus** [comment]
Лень 1 раз посмотреть ID основы? (Да и вроде можно уже буквами)

**Comment by raywave** [comment]
готвто
