### ISSUE TITLE
Перестала работать авто передача коинов.

### ISSUE THREAD

**Issue by Fomikus** [cursedseal/VCoinX#178]
После обновы до 1.3.7 перестала работать авто-передача коинов (Через bat задавал -t -to -ti -tperc). В конфиге тоже вроде все поставил - не работает.

**Comment by TheDeaX-Lab** [comment]
@Fomikus он знает. Удали восклицательный знак на 111 строке

**Comment by Fomikus** [comment]
Аргумент по скорости передачи не задается еще, каждый момент если баланс не равен 0 - передает

**Comment by raywave** [comment]
выпустил минификс
