### ISSUE TITLE
Покупает квантовый компьютер вместо датацентра

### ISSUE THREAD

**Issue by alexeyShirchkov** [cursedseal/VCoinX#18]
Аргументы: "-autobuy -autobuyItem datacenter"

Что я делаю не так?

P.S с аргументами "-autobuyItem datacenter" вообще ничего не покупает

**Comment by raywave** [comment]
Пока-что не используйте аргументы, пожалуйста.

Я ввел возможность покупки нескольки предметов, аргументы фиксану позже.

**Comment by alexeyShirchkov** [comment]
Принято, проинформируй пж как исправишь)

**Comment by raywave** [comment]
пофиксил частично, через аргументы закупка множества не работает, но один параметр указать можно и он будет работать
