### ISSUE TITLE
ID аккаунта НЕ ДЕЛИТАЙТЕ ПЛЕЗ

### ISSUE THREAD

**Issue by Sperma4ez** [cursedseal/VCoinX#181]
Да ало, у меня 7 винда, у меня не показывает в названии окна айди, боже...
Можете, пожалуйста, ПРОШУ ВАС, добавить функцию для копирования ID в буфер..

**Comment by Fomikus** [comment]
Запиши раз и навсегда в 1 файлик все ID`ы и все

**Comment by oplexz** [comment]
Когда скрипт запущен пишешь "i", выделяешь айди левой кнопкой мыши, после кликаешь правой кнопкой мыши. Готово, айди в буфере.
