### ISSUE TITLE
Нету задержки по передаче коинов

### ISSUE THREAD

**Issue by Fomikus** [cursedseal/VCoinX#182]
Передает - как только сможет
![image](https://user-images.githubusercontent.com/49315158/55745838-3af8b100-5a49-11e9-9a4c-87afea2fb690.png)
(В параметрах запуска (в .bat файле) и в botconfig`e стоит значение в 600 (Менял и до 600000))
В 111 строке менял transferInterval на 600 - тоже самое

**Comment by Fomikus** [comment]
Коины доходят не смотря на ошибку*

**Comment by XzzetiX** [comment]
типо коины доходяь но не тратятся?

**Comment by Fomikus** [comment]
Типо они тратятся и доходят каждую секунду, несмотря на задержку

**Comment by XzzetiX** [comment]
эммм

**Comment by raywave** [comment]
хз в чем проблема пока что, про доходят несмотря на ошибку фикс в 1.3.8 будет, ибо там накосячил в коде

**Comment by XzzetiX** [comment]
напиши ti и напиши 3600 это каждый час передача

**Comment by raywave** [comment]
попробуй изменить botconfig.js, я хз. фикса пока не придумал, закрою.
