### ISSUE TITLE
minCoins is not defined

### ISSUE THREAD

**Issue by oplexz** [cursedseal/VCoinX#188]
![image](https://user-images.githubusercontent.com/12859907/55772784-69e94400-5a96-11e9-851f-d88b789d89ff.png)
![image](https://user-images.githubusercontent.com/12859907/55772806-81283180-5a96-11e9-893d-168e181f6c99.png)
index.js:119

**Comment by raywave** [comment]
дубликат

**Comment by oplexz** [comment]
![image](https://user-images.githubusercontent.com/12859907/55773105-df094900-5a97-11e9-9ccb-d086622b7d46.png)
?

**Comment by Axteity** [comment]
> ![image](https://user-images.githubusercontent.com/12859907/55773105-df094900-5a97-11e9-9ccb-d086622b7d46.png)
> ?

https://github.com/cursedseal/VCoinX/issues/182
