### ISSUE TITLE
Прошу, сделайте уже адекватный перезапуск.

### ISSUE THREAD

**Issue by iamwh0iam** [cursedseal/VCoinX#190]
Если в аккаунт заходят, то бот должен сам переподключится, но он делает это всего 2 раза, потом пишет что через 10 секунд будет выполнен перезапуск и всё, перезапуска не происходит. Приходится вручную писать несколько раз run чтобы зашло. Иногда пишет десятки-сотни раз ошибку 200 и опять же приходится вручную писать run чтобы всё заработало. Это необходимо автоматизировать.
![Screenshot_6](https://user-images.githubusercontent.com/48156190/55796694-498baa80-5ad3-11e9-8d17-ebdeb7e836a9.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/48156190/55796695-4a244100-5ad3-11e9-9714-1d68d44287df.jpg)

**Comment by raywave** [comment]
в процессе, завтрашний апдейт как минимум, через неделю как максимум.

если не закроют VK Coin, естественно
