### ISSUE TITLE
Оптимальность умной покупки

### ISSUE THREAD

**Issue by vvd170501** [cursedseal/VCoinX#191]
Возможно, стоит изменить алгоритм умной покупки (например, выбирать ускорение в зависимости от текущей скорости, а не по цене за 1 коин/тик). Вариант алгоритма, реализованный сейчас, никогда не будет покупать ускорители с маленьким бонусом (курсор/видеокарта/стойка видеокарт). Например, при начальной цене в 0.001 коин и бонусе 0.01 коин/тик суммарная цена будет порядка 1e8 коинов, т.е. такая покупка бессмысленна

**Comment by vvd170501** [comment]
К тому же, функция mathPrice, которая используется для расчета цены, может выдавать неправильный результат. Цена за n ускорений с начальной ценой p примерно равна p + p*1.3 + ... + p*1.3^(n-1) = p*(1.3^n - 1)/(1.3-1). Функция же считает только цену последнего ускорителя, т.е. p*1.3^(n-1).

**Comment by raywave** [comment]
сделай фикс и в pr кинь, не я писал алгоритм
