### ISSUE TITLE
смартбай не работает

### ISSUE THREAD

**Issue by iamwh0iam** [cursedseal/VCoinX#195]
![BDh_YKyl_w4](https://user-images.githubusercontent.com/48156190/55820086-f0d40600-5b02-11e9-9812-953e05a7982e.jpg)

**Comment by Fomikus** [comment]
А то что скорость меняется - не?

**Comment by iamwh0iam** [comment]
> А то что скорость меняется - не?

каво?раньше смартбай нормально работал и покупал все за 5 секунд, сейчас же явно он багнулся и нужен фикс, как можно скорее

**Comment by raywave** [comment]
раз в 15 сек, в некст обнове добавлю возможность выбора интервала.
