### ISSUE TITLE
Smartbuy, autobuy

### ISSUE THREAD

**Issue by DreyStarkov** [cursedseal/VCoinX#198]
У меня вообще не работает смартбай и автопокупка, как и у некоторых других пользователей. Что делать?

**Comment by milkyklim** [comment]
В файле botconfig.json поставь: `"smartBuy": true`.

**Comment by DreyStarkov** [comment]
Пробовал, но все же не работает.

**Comment by pro100creepeer** [comment]
Было бы неплохо добавить возможность ограничения прокачки скорости (в Мультиботе есть реализация)

**Comment by milkyklim** [comment]
Заведи под это отдельный issue @pro100creepeer!

**Comment by milkyklim** [comment]
@DreyStarkov 

Какая система windows или linux?
В консоли есть хоть какие-то ошибки?

**Comment by DreyStarkov** [comment]
Винда, ошибок нет. Просто ввожу команду, а ничего не происходит, только написано, что умная покупка включена и все. Хотя коинов достаточно и в приложении через телефон могу купить все ускорения.

**Comment by milkyklim** [comment]
Версия самая свежая? Если да, то дальше не помогу, нет под руками Винды.

**Comment by DreyStarkov** [comment]
Версия последняя.

**Comment by lowkeypriority** [comment]
@DreyStarkov Кажется, ты должен ещё команду `pcb` написать, чтобы выставить процент выделенный на "умную покупку"

**Comment by DreyStarkov** [comment]
Это тоже пробовал, не получилось.

**Comment by lowkeypriority** [comment]
Довольно странно, а что пишет? И какая версия VcoinX?
У меня 1.3.7 -- всё нормально

**Comment by lowkeypriority** [comment]
Извини, вверху увидел, что последняя

**Comment by DreyStarkov** [comment]
![E4k_PrzqkWo](https://user-images.githubusercontent.com/49451038/55831954-9d7fa900-5b3e-11e9-9221-4d940afb2104.jpg)

**Comment by lowkeypriority** [comment]
@DreyStarkov limit coins устанавливал? (`setlimit`)

**Comment by DreyStarkov** [comment]
Нет

**Comment by lowkeypriority** [comment]
> Нет

ну так установи на ~~10млн или сколько тебе там надо~~ 1000 хватит, так как это ты предел коинов\тик устанавливаешь
`setlimit` или `sl` - установить лимит коинов / тик, до которого будет рабоать авто-закупка и умная покупка.

**Comment by DreyStarkov** [comment]
Спасибо.
