### ISSUE TITLE
Ошибки onBrokenEvent и onOffline

### ISSUE THREAD

**Issue by samespoon** [cursedseal/VCoinX#2]
Сервер вроде уже починили, но всё равно вылазят эти ошибки:
![Безымянный](https://user-images.githubusercontent.com/43492493/55518237-b72b7700-568c-11e9-8259-b183a0ff24fc.png)
Upd: Разобрался, ссылку указал неправильную.

**Comment by Kooteech** [comment]
Постоянная 502ая.
![Безымянный](https://user-images.githubusercontent.com/43064840/55521429-e81aa480-56aa-11e9-8b18-25a358f66cfc.png)

**Comment by raywave** [comment]
Перенес все на новые сервера, для оригинальной версии вышло обновление, пока я спал.

Фикс, закрыто.

**Comment by cursedseal** [comment]
ч
