### ISSUE TITLE
Новый фикс, выпущенный 10 минут назад, не работает. [onBrokenEvent]

### ISSUE THREAD

**Issue by ghetter** [cursedseal/VCoinX#20]
Спокойно работала, при строке "Вышло новое обновление". Решил обновить, новая версия не работает, так еще и старая перестала. Install Packages.bat в новой версии пробовал установить, не хелпануло, не удивительно)
Upd: 1:30 (Фикс 5 минут назад) ;
Ничего так и не заработало, теперь не пишет, что профиль загружен, а так же появилась новая строка "OnOffline" помимо "OnBrokenEvent":
Flood
`[05.04.2019 01:31:50]: Производится запуск VCoinX.`
`[05.04.2019 01:31:50]: VCoinX был успешно запущен.`
`[05.04.2019 01:31:50]: onBrokenEvent`
`[05.04.2019 01:31:50]: onOffline`

**Comment by svyanov** [comment]
+++ Новая версия не работает

**Comment by raywave** [comment]
фикс сервера в процессе.
