### ISSUE TITLE
Цена

### ISSUE THREAD

**Issue by Akionka** [cursedseal/VCoinX#200]
Умная покупка при запуске бота пишет, что считает, что круто было бы купить ДЦ за 1 605,920 (одна тыща шесот пять с копейками)
![image](https://user-images.githubusercontent.com/42269025/55831818-b4ad9f00-5b1c-11e9-8a06-28003e7aa541.png)
Хотя на мой прокачке столько дц стоить не может. Затем я зашел в приложение с телефона и увидел, что дц стоит 1 605 919 , 548.
![image](https://user-images.githubusercontent.com/42269025/55831991-2f76ba00-5b1d-11e9-9bd8-310dfdc47cc5.png)

**Comment by lowkeypriority** [comment]
@Akionka ~~как бы тысячные доли коина пишутся после точки, а не запятой (зяпятой разделяются группы рязрядов)~~
Так, извините, всё таки это проблем со смещением запятой
