### ISSUE TITLE
Ошибка при запуске Бота Termux и Linux

### ISSUE THREAD

**Issue by Linad-official** [cursedseal/VCoinX#201]
При запуске бота после гита на термукс, ошибка мол. "нет токина" ну норм думаю я чекаю папку, конфиги не распокованы, вписываю токин, та же ошибка. Хотя на винде всё норм!

**Comment by lowkeypriority** [comment]
Файлы были сохранены?
"Старую" консольку закрыли?
Можно скрин?

**Comment by ja4ert** [comment]
![Screenshot_20190409-234259](https://user-images.githubusercontent.com/44258135/55833904-520ad200-5b21-11e9-9ade-f1c358d84ed7.png)

**Comment by Linad-official** [comment]
![oDbvvPTCqA0](https://user-images.githubusercontent.com/49456590/55834158-e7a66180-5b21-11e9-8690-8f7e0c08d73e.jpg)


> Файлы были сохранены? 
> "Старую" консольку закрыли? 
> Можно скрин?

вот

**Comment by lowkeypriority** [comment]
@Linad-official эм... у вас конфиг не так называется -- должно быть `userconfig.json` вместо `userconfig.example.json`

**Comment by lowkeypriority** [comment]
тоже самое с `botconfig.json`

**Comment by TemaSM** [comment]
@Linad-official @ja4ert исправлено в #203 👌
