### ISSUE TITLE
не робит фарм на группу

### ISSUE THREAD

**Issue by azqswxdcefrvgtb** [cursedseal/VCoinX#202]
![Screenshot_21](https://user-images.githubusercontent.com/48870049/55835337-96e43800-5b24-11e9-8f68-77a7410f2b91.jpg)
![Screenshot_22](https://user-images.githubusercontent.com/48870049/55835338-96e43800-5b24-11e9-9af9-e1e1470c42a0.jpg)

**Comment by Linad-official** [comment]
https://github.com/cursedseal/VCoinX#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0

**Comment by TemaSM** [comment]
@azqswxdcefrvgtb выше скинули ссылку, которая перебрасывает на абзац с инструкцией как сделать расширенный токен. После применения такого токена VCoinX будет корректно работать.
