### ISSUE TITLE
Unexpected server response: 502

### ISSUE THREAD

**Issue by r00t-Taurus** [cursedseal/VCoinX#205]
У меня пару аккаунтов, один работает, на другом стало появляться это:
```
                Через 10 секунд будет выполнен перезапуск.
[10.04.2019 04:13:16]: VCoinX загружается...
На стороне сервера возникла ошибка: Unexpected server response: 502
[10.04.2019 04:13:16]: [ОШИБКА]: Пользователь отключен от сервера.
                Через 10 секунд будет выполнен перезапуск.
[10.04.2019 04:13:36]: VCoinX загружается...
На стороне сервера возникла ошибка: Unexpected server response: 502
[10.04.2019 04:13:37]: [ОШИБКА]: Пользователь отключен от сервера.
                Через 10 секунд будет выполнен перезапуск.
[10.04.2019 04:13:37]: [ОШИБКА]: Достигнут лимит попыток подключиться к серверу.
```
И так вечно, в чем проблема?

**Comment by kilabeez** [comment]
если ты попробуешь зайти с того аккаунта в сервис через приложение, то оно не загрузится, хуй знает почему, у меня сейчас так же

**Comment by trrofim** [comment]
Ребят памагитеее, у меня такая же фигня

**Comment by Akula2112** [comment]
Тоже перестало грузить через сервесы

**Comment by TemaSM** [comment]
Разрабы VK Coin ведут какие-то разработки и технические работы у себя на серверах, поэтому время от времени некоторые пользователи `VCoinX` могут испытывать проблемы с `На стороне сервера возникла ошибка` - пробуйте перезапускать `VCoinX` через некоторое время.

![image](https://user-images.githubusercontent.com/5501615/55853650-b1d99b00-5b6a-11e9-9677-d01cc76c34af.png)
