### ISSUE TITLE
Ошибка код: 509

### ISSUE THREAD

**Issue by Dima005** [cursedseal/VCoinX#206]
Что делать?

**Comment by TheMrMes109** [comment]
Видать ВК начали банить акичи и обнулять баланс. На всех аках (2 штуки) с которых был бот больше не заходит в Vk Coin и на акич куда я сливал все коины тоже. На том который был не задействован все работает

**Comment by TemaSM** [comment]
Разрабы VK Coin ведут какие-то разработки и технические работы у себя на серверах, поэтому время от времени некоторые пользователи `VCoinX` могут испытывать проблемы с `На стороне сервера возникла ошибка` - пробуйте перезапускать `VCoinX` через некоторое время.

![image](https://user-images.githubusercontent.com/5501615/55853650-b1d99b00-5b6a-11e9-9677-d01cc76c34af.png)
