### ISSUE TITLE
Ошибки с Websocket

### ISSUE THREAD

**Issue by TheDeaX-Lab** [cursedseal/VCoinX#207]
https://ibb.co/61MKGkf
https://ibb.co/hMN2r8W
https://ibb.co/5Fws2th

**Comment by Kuzuru** [comment]
Та же ошибка после обновы пришла

**Comment by TemaSM** [comment]
Это из-за того что разрабы VK Coin мутят обновления на своих тестовых серверах.
Если это не уйдет, будем делать патчи.

**Comment by ghost** [comment]
проблемы фиксануть нет так-то, буквально в одну строчку. особенно с учетом того что бот на ноде.

**Comment by TemaSM** [comment]
@tggdesu разрабы VK Coin делают защиту от ботов. Заставляют ботов исполнять определенный код, который должен возвращать число. Проблема в том что данный код можно исполнить только в браузере (приложение ВК на телефоне имеет браузерный контейнер, поэтому там VK Coin работает).
Сейчас ищу варианты реализации.

**Comment by ghost** [comment]
@TemaSM а я типо не знаю, да? чекни мои репы

**Comment by TemaSM** [comment]
@tggdesu чекнул, пасиб 👍

**Comment by TemaSM** [comment]
Проблема решена в релизе: https://github.com/cursedseal/VCoinX/releases/tag/v1.3.11
