### ISSUE TITLE
неправильный логин или пароль

### ISSUE THREAD

**Issue by xRy0** [cursedseal/VCoinX#209]
![image](https://user-images.githubusercontent.com/43928323/55859278-6a5b0b00-5b7a-11e9-9d67-6fb225c6532d.png)
логин и пароль верные(проверил копипастом из конфига в вк) пробелов и других лишних символов нету.

**Comment by ghost** [comment]
Если пароль/логин содержат обратные слэши то node js может их не пропустить, а если ошибок от движка нет, то я хз и надо смотреть баг или индивидуальный случай это.

**Comment by Neutrat** [comment]
Такая же ошибка. Но вместо номера я использовал емаил, хотя раньше с ним работало.

**Comment by raywave** [comment]
одно из решений выше, второе - изменить раскладку.
