### ISSUE TITLE
Аргумент айди группы.

### ISSUE THREAD

**Issue by patserkovsky** [cursedseal/VCoinX#210]
Сделайте возможность запуска лаунчера с аргументом, который принимает айди группы.

**Comment by badnike4567** [comment]
Вообще то в userconfig есть аргумент с id группы...

**Comment by patserkovsky** [comment]
> Вообще то в userconfig есть аргумент с id группы...

Хочу написать батник, который просто запускается и ничего больше не надо делать, не изменять ни юзерконфиги, ни ботконфиги и тд.
__________________________________________
А так аргумент для запуска нашёл в index.js. Проблема исчерпана.
