### ISSUE TITLE
Новая версия

### ISSUE THREAD

**Issue by Kuzuru** [cursedseal/VCoinX#213]
Происходит ошибка web сокета

**Comment by Kuzuru** [comment]
![image](https://user-images.githubusercontent.com/49472529/55870332-c8e7af80-5ba1-11e9-9be5-f434d9a2c7ee.png)

**Comment by Kuzuru** [comment]
После чего, следующее: 
![image](https://user-images.githubusercontent.com/49472529/55870358-d69d3500-5ba1-11e9-9c9e-955b56ddbc9e.png)

**Comment by JDM170** [comment]
Установи новую версию из раздела "releases"

**Comment by Kuzuru** [comment]
> Установи новую версию из раздела "releases"

благодарю, все работает
