### ISSUE TITLE
Ломается после открытия вкоин с другого устройства

### ISSUE THREAD

**Issue by diggi543** [cursedseal/VCoinX#216]
После открытия клиента ВК с вкоином бот пытается переподключиться и падает с ошибками
**connect ECONNREFUSED 95.213.18.83:443**

**Comment by badnike4567** [comment]
Попробовал, у меня работает стабильно. Наверное индивидуальная ошибка какая-то

**Comment by diggi543** [comment]
@badnike4567 индивидуальная ошибка у 5-ти человек, именно

**Comment by diggi543** [comment]
Заменил количество попыток на 999 - заработало. Вывод: бот меняет сервер на какой-то нерабочий не дождавшись ответа от прошлого

**Comment by kurigvit** [comment]
> Заменил количество попыток на 999 - заработало. Вывод: бот меняет сервер на какой-то нерабочий не дождавшись ответа от прошлого

Как ты это сделал?

**Comment by diggi543** [comment]
@kurigvit в index.js в двух местах 
```
(lastTry >= numberOfTries)
```
Заменил **numberOfTries** на **999** 
В теории, ему должно быть достаточно и около 5-10 попыток, но это не точно

**Comment by raywave** [comment]
фикс
