### ISSUE TITLE
Другая ошибка с новым фиксом :(

### ISSUE THREAD

**Issue by xterlo** [cursedseal/VCoinX#22]
![Screenshot_2019-04-04-22-47-36-643_org connectbot](https://user-images.githubusercontent.com/36822079/55584184-56ec1200-572c-11e9-8e1d-bd8f3cf9e4ee.png)

**Comment by 0xl0cal** [comment]
нихуя ты гений, я также само сделаю

**Comment by xterlo** [comment]
:)

**Comment by raywave** [comment]
сервера в процессе.
