### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by jmibegi2h** [cursedseal/VCoinX#224]
> 1. Распишите ошибки при авторизации, неправильный логин или пароль или токен! Также при старте чтобы окно не закрывалось если происходит какая-то ошибка, потому что Невозможно определить какая именно!
> 2. Конечно отправка логов вам это прикольная тема, но н**** оно надо? Это долгая загрузка прям нравится! Особенно когда у тебя много аккаунтов. Или сделайте возможность чтобы человек сам выбирал, отправлять вам логин или нет, потому что когда ты используешь одного Бота, то конечно на это никак не влияет на процесс.

**Comment by jmibegi2h** [comment]
> 1. Распишите ошибки при авторизации, неправильный логин или пароль или токен! Также при старте чтобы окно не закрывалось если происходит какая-то ошибка, потому что Невозможно определить какая именно!
> 2. Конечно отправка логов вам это прикольная тема, но н**** оно надо? Это долгая загрузка прям нравится! Особенно когда у тебя много аккаунтов. Или сделайте возможность чтобы человек сам выбирал, отправлять вам логин или нет, потому что когда ты используешь одного Бота, то конечно на это никак не влияет на процесс.

**Comment by raywave** [comment]
1. если все делать по инструкции, то все будет работать.
2. отправка логов создана для того, чтоб пофиксить ошибки, которые возникают у людей, крые не знают как отправить ошибку.
