### ISSUE TITLE
Не работает "smartbuy" 

### ISSUE THREAD

**Issue by Invis1on** [cursedseal/VCoinX#226]
При запуске бота и вводя команду "smartbuy", бот пишет, что "Умная закупка: включен
Автозакупка: Выключен" дальше ноль реакции, на балансе есть 1кк коинов и у бота 0 тиков в секунду.

**Comment by DiFFoZ** [comment]
Поставь лимит TPS `setlimit 1000` должно помочь

**Comment by Invis1on** [comment]
Нет TPS, есть только CPS

**Comment by Invis1on** [comment]
Нашёл, извиняюсь, сейчас проверю

**Comment by raywave** [comment]
^ фикс выше
