### ISSUE TITLE
Создание определенного паттерна автозакупки

### ISSUE THREAD

**Issue by kirusfg** [cursedseal/VCoinX#28]
Повторение определенного паттерна автозакупки:
1. Создать массив, куда юзер вписывает свой порядок закупки:
var autoBuyPattern = ["quantum_pc", "quantum_pc", "quantum_pc", "quantum_pc", "server_vk", "server_vk", "server_vk", "server_vk", "server_vk", "quantum_pc", "datacenter"];
2. В функции autobuyitem, или в отдельной функции, проходить по этому списку заданное или бесконечное количество раз.

**Comment by raywave** [comment]
идея неплохая.

**Comment by kirusfg** [comment]
Ну и покупку нескольких ускорителей за одну команду buy не помешало бы сделать

**Comment by raywave** [comment]
покупку за одну команду сделал, насчет паттерна делать не буду, ввел смартбай.
