### ISSUE TITLE
Выдает ошибку при запуске.

### ISSUE THREAD

**Issue by Ricanoff** [cursedseal/VCoinX#29]
![image](https://user-images.githubusercontent.com/49291229/55587177-75094080-5733-11e9-9548-ae04d2dcea0f.png)

**Comment by DpO4uLa** [comment]
Файл index.js

Заменить 
URLWS = URLWS.replace ("coin.vkforms.ru", "coin.w5.vkforms.ru"); 
На 
URLWS = URLWS.replace ("coin.vkforms.ru", "coin-without-bugs.vkforms.ru");

PS Фикс с оригинала

**Comment by raywave** [comment]
Добавлен свитчер серверов. Фикс.
