### ISSUE TITLE
Удалось запустить

### ISSUE THREAD

**Issue by alexeyShirchkov** [cursedseal/VCoinX#30]
Файл index.js

Заменить
URLWS = URLWS.replace("coin.vkforms.ru", "coin.w5.vkforms.ru");
На
URLWS = URLWS.replace("coin.vkforms.ru", "coin-without-bugs.vkforms.ru");

P.S Фикс с оригинала
Временное решение, ждем обновления)

**Comment by kama2345621** [comment]
а где это заменить?

**Comment by alexeyShirchkov** [comment]
> а где это заменить?

Еще раз прочитай.

**Comment by vovak155** [comment]
onBrokenEvent вылазит дальше.
Единственный фикс - старая версия и замена версии в файле.

**Comment by alexeyShirchkov** [comment]
> onBrokenEvent вылазит дальше.
> Единственный фикс - старая версия и замена версии в файле.

Зайди с телефона в приложение и выйди, мне помогает

**Comment by azqswxdcefrvgtb** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/48870049/55588481-8f90e900-5736-11e9-9822-0ba8e41db6e6.jpg)
всё робит

**Comment by alexeyShirchkov** [comment]
> ![Screenshot_19](https://user-images.githubusercontent.com/48870049/55588481-8f90e900-5736-11e9-9822-0ba8e41db6e6.jpg)
> всё робит

**Comment by vovak155** [comment]
бля не помогло. зашёл с телефона и вышел таже хуета

**Comment by vovak155** [comment]
ну вот на старой версии всё было окей, ща скачал старую и вылазит OnBrokenEvent, мда...

**Comment by vovak155** [comment]
пофиксилось через хуеву тучу времени, спасибо

**Comment by raywave** [comment]
добавлен свитчер серверов, закрыто.
