### ISSUE TITLE
Автозакупка

### ISSUE THREAD

**Issue by Thedrezik** [cursedseal/VCoinX#31]
Каждый апгрейд увеличивает доход в 2,3,5 раз от пред идущего - эти цифры это коэффициент.
Нужно создать циклическое сравнение последующего с пред идущим умноженное на коэффициент,если пред идущее больше то покупается(апгрейд который стоял например вторым) ,если меньше то покупается пред идущее (стоял первым).
И так это все прогоняется много раз,и будет по умному апгрейдить наши оборудования

**Comment by Thedrezik** [comment]
И еще сделайте в ручной закупке слова покороче, а то бесит полностью писать

**Comment by raywave** [comment]
сложна
спасибо
подумаю
мы вам перезвоним
