### ISSUE TITLE
Не ворк :)))

### ISSUE THREAD

**Issue by xterlo** [cursedseal/VCoinX#32]
Мб я конечно тупой, но 
![Screenshot_2019-04-05-00-23-50-212_org connectbot](https://user-images.githubusercontent.com/36822079/55589633-645bc900-5739-11e9-8651-07551363b3ac.png)

**Comment by svyanov** [comment]
[05.04.2019 00:27:44]: Производится запуск VCoinX.
[05.04.2019 00:27:45]: VCoinX был успешно запущен.
[05.04.2019 00:27:45]: [ОШИБКА]: onBrokenEvent
[05.04.2019 00:27:45]: [ОШИБКА]: onOffline

**Comment by lNavigatoRl** [comment]
Присоединяюсь к проблеме

**Comment by DpO4uLa** [comment]
в файле index.js строку с URLWS = URLWS.replace (бла бла бла) замени на URLWS = URLWS.replace ("coin.vkforms.ru", "coin-without-bugs.vkforms.ru");

**Comment by raywave** [comment]
добавлен свитчер серверов, закрыто.
