### ISSUE TITLE
Работа нескольких аккаунтов в потоке

### ISSUE THREAD

**Issue by L3Nya** [cursedseal/VCoinX#34]
Возможность добавить в конфиг несколько токенов, которые будут параллельно майнить ВКоины. Надоедает бегать между окнами и за всеми следить

**Comment by alexeyShirchkov** [comment]
> Возможность добавить в конфиг несколько токенов, которые будут параллельно майнить ВКоины. Надоедает бегать между окнами и за всеми следить

На xTCry чувак запулил коммит с такой возможностью

**Comment by L3Nya** [comment]
> > Возможность добавить в конфиг несколько токенов, которые будут параллельно майнить ВКоины. Надоедает бегать между окнами и за всеми следить
> 
> На xTCry чувак запулил коммит с такой возможностью

Спасибо, посмотрю

**Comment by raywave** [comment]
Если добавят в оригинале - добавлю в мод.

Закрыто.
