### ISSUE TITLE
Автоматический выбор выгодных ускорений

### ISSUE THREAD

**Issue by L3Nya** [cursedseal/VCoinX#35]
Бот сам должен выбирать более выгодные ускорения.
Например квантовый компьютер в 3 раза дешевле чем дата-центр, а 2 квантовых ПК == 1 дата-центру. => надо взять квантовый ПК.

**Comment by raywave** [comment]
https://github.com/cursedseal/VCoinX/issues/37#issuecomment-480085985

**Comment by caendeith** [comment]
Можно просто цену делить на то сколько производит улучшение и узнать теоретическую стоимость 1 коина в секунду и то улучшение чья теоретическая стоимость меньше то и должен покупать бот

**Comment by raywave** [comment]
перенес smartbuy
