### ISSUE TITLE
Вот

### ISSUE THREAD

**Issue by Thedrezik** [cursedseal/VCoinX#37]
Бот сам должен выбирать более выгодные ускорения.
Например квантовый компьютер в 3 раза дешевле чем дата-центр, а 2 квантовых ПК == 1 дата-центру. => надо взять квантовый ПК.

**Comment by raywave** [comment]
Да я бы это в первый день сделал если бы придумал алгоритм.

**Comment by ValMot** [comment]
Теоретически, здесь должно быть что-то посложнее, чем просто, покупать то, что дешевле.

Вариант получше: выгодность надо оценивать по цене за единицу скорости, например, считать стоимость самой маленькой части (0,001/сек) и сравнивать её с остальными, самую маленькую покупать.

Ещё более правильный вариант: к первому варианту брать в расчёт ещё и скорость текущего "майнинга", то есть считать, за сколько времени наберётся нужная сумма для покупки. Например, я могу купить +1 за 200k, но копить эти 200k я буду 3 часа, в то же время, я могу взять 2 по 0,5, и в итоге потрачу 201k. 
Но при втором раскладе, после первой покупки скорость возрастёт, и, следовательно, на набор второй части суммы я потрачу меньше времени, так что этот вариант более выгоден, если необходимо экономить время (а в этой игре, в первую очередь нужно исходить из экономии времени, а не денег). Но тут необходимо будет брать в расчёт и растущую цену после каждой покупки.

**Comment by WickedCicle** [comment]
> Да я бы это в первый день сделал если бы придумал алгоритм.

Не уверен, что вы не думали об этом, но всё же...

Берём изначальные значения цен. Пусть будет 2 и 3 монеты(для наглядности).
Так же мы знаем сколько раз они улучшены. Пусть 2 монеты улучшены n раз, а 3 монеты m раз.
Ищем наименьшее общее кратное. Для нашего случая 6 монет.
Тогда, для того чтобы взять 3 монеты:
2^n + 2^(n+1) +2^(n+2) > 3^m + 3^(m+1)
Для 2 монет соответственно:
2^n + 2^(n+1) +2^(n+2) < 3^m + 3^(m+1)

Количество слагаемых равно отношению НОК к изначальному значению цены.

Не знаю, как это будет в плане оптимизации. Просто предложил один из вариантов.
