### ISSUE TITLE
Предложения по улучшению

### ISSUE THREAD

**Issue by Peregof** [cursedseal/VCoinX#39]
1. Назови  батники, чтобы можно было понять, что за аккаунт стоит
2. Чтобы можно было вставить только  логин и пароль, без апи кея
3. Чтобы не нужно было плодить папки, а сделать всё из одной программы, то есть, как в ASF сделать конфиг для каждого аккаунта, скинуть все конфиги в одну папочку и не нужно будет плодить папки
4. Чтобы можно было с основного аккаунта раскидать по другим немного и наоборот со всех акков на один скинуть весь балланс
5. Сделать возможным вводить команды без остановки батника
6.  Ну и понятно выбирать, то что выгоднее в плане улучшения, но будет сложновато
7. Сделать общий баланс и общее количество коинов в секунду
8. Дополнении пункта 3 - можно сделать это из веб конфиг, опять же отсылка к ASF, там ты сам делаешь конфиг для бота, скачиваешь файл и переносишь в общую папку...

**Comment by TeenKode** [comment]
а я сделал текстовик со всеми токенами и батник, который его парсит и плодит окна с каждым из них под своим номером)

**Comment by TeenKode** [comment]
> Чтобы можно было с основного аккаунта раскидать по другим немного и наоборот со всех акков на один скинуть весь баланс.

Действительно, у всех ведь есть так называемый Ботмастер, то есть главый акк с коинами.
Можно написать макрос для скидывания с ботмастера каждому дочернему боту по энное количество коинов, для развития.

**Comment by SKUDi53** [comment]
Появилась идея,сделать что бы показывал топ среди друзей

**Comment by Pheren** [comment]
Добавьте сюда файл install.sh и launch.sh, чтобы можно было юзать в термуксе)

**Comment by Allespro** [comment]
> Добавьте сюда файл install.sh и launch.sh, чтобы можно было юзать в термуксе)

А что так тебе мешает использовать термукс? Установи ноду и всё. Потом запусти `node index.js -t твой-токен-от-вк`, если файл настроек пуст, или просто `node index.js` если добавил токен в настройки.

**Comment by Pheren** [comment]
Все сделал но пишет ошибку cannot find module "open", что это может быть?

**Comment by Allespro** [comment]
> Все сделал но пишет ошибку cannot find module "open", что это может быть?

Удали бота, и опять скачай. Исполни батник и всё будет. Модуль open в обнове появился

**Comment by TheDeaX-Lab** [comment]
Всем привет, могу ли я предложить свой вариант установки? А то неопытным людям слишком много телодвижений нужно))). Код не меняется но добавится ещё файл bat для windows а с linux дела с разными дистрибутивами сложнее

**Comment by vindi142** [comment]
> 2. Чтобы можно было вставить только логин и пароль, без апи кея
Собсна что мешает это сделать? Тут достаточно просто спросить сервер по ссылке из README и распарсить ответ в виде JSON.

**Comment by ghost** [comment]
> Чтобы можно было вставить только логин и пароль, без апи кея

Собсна что мешает разроботчику это реализовать ссылка есть в README.

**Comment by AlexseiSil** [comment]
Есть предложение в " Будушем " сделать интерфейс более простой

**Comment by ghost** [comment]
> Есть предложение в " Будущем " сделать интерфейс более простой

Проще некуда ибо консоль, хотя можно переписать бота на какой-нибудь c# или c++ ну и сделать всё на winforms, но тогда мы лишимся мульти-плаформенности.

**Comment by raywave** [comment]
1. нет, дубликат
2. мб
3. нет. дубликат
4. если введут поддержку мультиакков
5. и так лол
6. 1.2.5
7. ответ про мультиакки выше
8. ...

**Comment by AlexseiSil** [comment]
Не в том плане что сделать небольшую менюху  для более простого входа без всяких там настроек конфигов ,да нужно будет искать токен ,но это уже будет куда проще как я думаю


Отправлено из приложения "Почта" для Windows 10

От: vindi142
Отправлено: 7 апреля 2019 г. в 10:37
Кому: cursedseal/VCoinX
Копия: AlexseiSil; Comment
Тема: Re: [cursedseal/VCoinX] Предложения по улучшению (#39)

Есть предложение в " Будущем " сделать интерфейс более простой
Проще некуда ибо консоль, хотя можно переписать бота на какой-нибудь c# или c++ ну и сделать всё на winforms, но тогда мы лишимся мульти-плаформенности.
