### ISSUE TITLE
Identifier 'vConinWS' has already been declared        

### ISSUE THREAD

**Issue by awskt** [cursedseal/VCoinX#4]
root@ubuntu-s-4vcpu-8gb-sfo2-01:~/VCoinX# sh '2. launch.sh'                /root/VCoinX/index.js:53                                                   vConinWS.onMissClickEvent(_=> {                                            ^                                                                                                                                                     SyntaxError: Identifier 'vConinWS' has already been declared                   at createScript (vm.js:80:10)                                              at Object.runInThisContext (vm.js:139:10)                                  at Module._compile (module.js:616:28)                                      at Object.Module._extensions..js (module.js:663:10)                        at Module.load (module.js:565:32)                                          at tryModuleLoad (module.js:505:12)                                        at Function.Module._load (module.js:497:3)                                 at Function.Module.runMain (module.js:693:10)                              at startup (bootstrap_node.js:191:16)                                      at bootstrap_node.js:612:3

**Comment by raywave** [comment]
Баг был пофикшен пару версий назад, переустановите обновление.

**Comment by awskt** [comment]
Но у меня последняя версия 🤔
