### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by bloheey** [cursedseal/VCoinX#40]
Запускаю, работает, работает... вылетает ошибка onOffline и стопится, даже не пытается восстановиться. При другой ошибки да, он восстанавливается. https://i.imgur.com/JVDG1sT.png
Запущенно 2 окна, в одном все по маслу, а в другом эта хрень вылезает переодически.

**Comment by raywave** [comment]
посмотрю после школы.

**Comment by raywave** [comment]
фикс.
