### ISSUE TITLE
some ideas 

### ISSUE THREAD

**Issue by qKamina** [cursedseal/VCoinX#42]
Можно добавить несколько идей.

1. В строке названия программы где VKCoinX , можно добавить 2 вещи таких как версию программы и имя и фамилия с вк токен которых ты используешь пример: VKCoinX 1.1.9 - Vladimir Osetin

2. Сделать autobuy не просто 1 предмета как только у тебя хватает денег , а сделать какую-нибудь формулу которая сделает это лучше например сначала там 3 курсора -> 1 видеокарту -> 1 датацентр и тд

3. перенести с цмд на чтонибудь удобнее , могу помочь с этим если нужно

**Comment by raywave** [comment]
> 1. В строке названия программы где VKCoinX , можно добавить 2 вещи таких как версию программы и имя и фамилия с вк токен которых ты используешь пример: VKCoinX 1.1.9 - Vladimir Osetin

над этим подумаю, может не введу имя и фамилию, но версию введу точно.



> 2\. Сделать autobuy не просто 1 предмета как только у тебя хватает денег , а сделать какую-нибудь формулу которая сделает это лучше например сначала там 3 курсора -> 1 видеокарту -> 1 датацентр и тд

ну эту формулу еще нужно написать, как кто-нибудь напишет или даст подсказок или идей - напишу.



> 3\. перенести с цмд на чтонибудь удобнее , могу помочь с этим если нужно

не люблю интерфесы, они притягивают неадекватов.
можно просто довести до ума всю систему.

**Comment by raywave** [comment]
ввел абсолюнто все.

**Comment by raywave** [comment]
я думаю, ты победишь в конкурсе на 50 рубликов, дай свой вк.

**Comment by Peregof** [comment]
лол поч не я
