### ISSUE TITLE
Ошибки по серверам.

### ISSUE THREAD

**Issue by Kooteech** [cursedseal/VCoinX#43]
На всех серверах от 0 до 3 ошибки: 200, 404, 500, 502

**Comment by raywave** [comment]
нулевой сервак - сервер 1
первый сервер - сервер 2
второй сервер - сервер 3
третий сервер - оптимальный выбор между сервером 2 и сервером 3.

судя по ошибкам, подключаясь на третий сервер ты не подключился ни ко серверу 2, ни к серверу 3, тогда откуда взялся сервер 4? ниоткуда.

сервера лежат / что-то блокирует к ним доступ.
