### ISSUE TITLE
Свитчер все еще не работает)

### ISSUE THREAD

**Issue by alexeyShirchkov** [cursedseal/VCoinX#45]
![dee7486646](https://user-images.githubusercontent.com/49288658/55607567-939c2580-578d-11e9-9b14-49411cbf23e8.jpg)

После правок, смог приконнектиться и все заработало.

**Comment by raywave** [comment]
работает

**Comment by raywave** [comment]
пофикшу реплейс, прошлую обнову чекай

**Comment by alexeyShirchkov** [comment]
> пофикшу реплейс, прошлую обнову чекай

я скачал последний коммит. Пока не поправил USER_ID и replace, у меня не стартовало. Он CHANEL рассчитывал в NaN. Да и по любому условию replace не срабатывал, потому ссылка оказывалась не рабочая

**Comment by vovak155** [comment]
лёха блинб чо там как пофиксить бесконечный реконнект

**Comment by raywave** [comment]
1.2.5 фикс
