### ISSUE TITLE
Обновился и перестало работать

### ISSUE THREAD

**Issue by svyanov** [cursedseal/VCoinX#46]
> [05.04.2019 10:16:53]: VCoinX загружается...
Unexpected server response: 404
[05.04.2019 10:16:53]: [ОШИБКА]: Пользователь отключен от сервера.
                Через 10 секунд будет выполнен перезапуск.

**Comment by skidunion** [comment]
Бот выбирает "NaN" канал 
`formatWSS:  wss://coin-without-bugs.vkforms.ru/channel/NaN`

**Comment by skidunion** [comment]
Можно добавить следующий код в `index.js`
```
let id = (await vk.api.users.get())[0]["id"];
```
заменяя `let id = (await vk.api.users.get())[0]`

**Comment by Slivondiy** [comment]
> Можно добавить следующий код в `index.js`
> 
> ```
> let id = (await vk.api.users.get())[0]["id"];
> ```
> заменяя `let id = (await vk.api.users.get())[0]`

**Спасибо помог.**
Сначала выдала ошибку что обнаружен Brokenbrake, а потом перезагрузил сервер и запустился!

**Comment by raywave** [comment]
фикс. 1.2.5
