### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by awskt** [cursedseal/VCoinX#5]
Error: Cannot find module 'vk-io'                                              at Function.Module._resolveFilename (module.js:547:15)                     at Function.Module._load (module.js:474:25)                                at Module.require (module.js:596:17)                                       at require (internal/module.js:11:18)                                      at Object.<anonymous> (/root/VCoinX/index.js:4:9)                          at Module._compile (module.js:652:30)                                      at Object.Module._extensions..js (module.js:663:10)                        at Module.load (module.js:565:32)                                          at tryModuleLoad (module.js:505:12)                                        at Function.Module._load (module.js:497:3)

**Comment by raywave** [comment]
напишу решение, если у кого то будет такое же: отключите дефендер винды.
