### ISSUE TITLE
Баг с отображением цены

### ISSUE THREAD

**Issue by Kooteech** [cursedseal/VCoinX#50]
Legacy release.
![price](https://user-images.githubusercontent.com/43064840/55621262-34f39d80-57c7-11e9-85bd-4eb49afa77ea.png)

**Comment by Dpo4uLa** [comment]
у тебя просто не хватает денег на улучшения, которые он не показывает. как только деньги на улучшения будут, бот сразу покажет, что можно купить

**Comment by skidunion** [comment]
Не баг, а фича (отображаются только те предметы, на которые у тебя хватает койнов)

**Comment by raywave** [comment]
не баг а фича, легаси буду фиксить в последнюю очередь
