### ISSUE TITLE
Дополнения обновления.

### ISSUE THREAD

**Issue by LifeViwer** [cursedseal/VCoinX#51]
1. Сократить логирования консоле. 
Это убрать длинную строчку даты оставить только например время.
Так же сократить количество койнов, чтоб писалось просто например "Баланс"
P.s. Сам смогу передать, но автору предлагаю, прислушаться если понравиться то сократить)
2. Перевод полностью всего баланса, в строке "Сколько" чтоб можно было написать "All" или просто 999999 и чтоб скрипт понял что это нужно списать полностью весь баланс сколько есть в данную секунду.
3. Добавить удобный массовый запуск для токенов например есть 50 токенов чтоб сделал пару команд и всё у тебя сразу все 50 шт. включились.
4. Добавить команду запроса скорости "Speed" и тебе чтоб выдавала, ваша скорость 55.1 Койн/Сек.
5. Внешний вид. я тупой или что, но не могу понять, как подписать можно окна коммнадной строки, чтоб например было "Пупкин Сергей ID2315232" А не длинное название Node.js command promopt......

Пока всё, дальше больше всяких прикольных и нужных вещей, кто согласен ставьте  лайк чтоб автор быстрее их реализовал.

**Comment by Yexeed** [comment]
ну пулл организуй, если можешь сам переделать, помоги автору

**Comment by Kooteech** [comment]
Подписать окна можно изменением батника:
 title *название* 
@CheckHack

**Comment by Yexeed** [comment]
@Kooteech, какой ты умняша! первое, как ты передашь в уже запущенный батник имя окна, если скрипт после запуска только узнаёт айди и имя\фамилию страницы.
второе, по линуксу что скажешь?

**Comment by Kooteech** [comment]
@Yexeed
Берёшь и ручками пишешь)
Для линя уже давно всё написано:
*/etc/bash.bashrc*
`function set-title() {
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1=${ORIG}${TITLE}
}`

**Comment by raywave** [comment]
2. сделано, давно уже. над остальным подумаю.
