### ISSUE TITLE
Предложение по улучшению автопокупки.

### ISSUE THREAD

**Issue by BornikReal** [cursedseal/VCoinX#52]
Суть в чем - программа считывает цены на каждое из улучшений и переводит в цену за 0,001. То есть Датацентр дает 1 к/с и стоит у игрока 16000, чтобы перевести в цену за 0,001, мы делим 16000 на 1000 (1/1000=0.001) и получим 16.  Квантовый компьютер стоит 7000 и дает 0,5 к/с - мы делим 7000 на 500 (0.5/500=0,001) и получаем 14. Из полученного мы делаем вывод, что в данном случае покупка Квантового компьютера будет выгодней, хоть и даст всего +0,5 к/с, в отличии от 1 к/с. Такая операция будет проводиться со всеми улучшениями, вплоть до курсора, после каждой покупки, выполненной игроком или программой. Надеюсь, я свою идею вам донес.

**Comment by makcimbx** [comment]
Это называется SmartBuy, в VCoin она уже есть, остаётся ждать пока тут добавят. Хотя всё равно новая версия не работает с ошибкой 404.

**Comment by BornikReal** [comment]
> Это называется SmartBuy, в VCoin она уже есть, остаётся ждать пока тут добавят. Хотя всё равно новая версия не работает с ошибкой 404.

Она вообще у кого-нибудь работает?

**Comment by makcimbx** [comment]
Там в pull requests выложили решение ошибки, но на самом деле всё равно пока смарт бай не добавят, лучше юзать VCoin версию

**Comment by Thedrezik** [comment]
Киньте ссылку там где смартбай есть

**Comment by BornikReal** [comment]
> Там в pull requests выложили решение ошибки, но на самом деле всё равно пока смарт бай не добавят, лучше юзать VCoin версию

А как в новой версии включить SmartBuy?

**Comment by raywave** [comment]
smartbuy перенесен в 1.2.5
