### ISSUE TITLE
Дополнение к обнове

### ISSUE THREAD

**Issue by danikone** [cursedseal/VCoinX#55]
Возможность давать названия окнам (чтобы было понятно, где какой акк)

**Comment by Kooteech** [comment]
Уже есть в пул реквестах под винду от меня. Жду, пока @cursedseal чекнет перед мержем

**Comment by danikone** [comment]
> Уже есть в пул реквестах под винду от меня. Жду, пока @cursedseal чекнет перед мержем

Круто)

**Comment by raywave** [comment]
будет в 1.2.7
