### ISSUE TITLE
Массовый запуск ботов.

### ISSUE THREAD

**Issue by longfest** [cursedseal/VCoinX#56]
Всем привет. Хочу узнать, как можно автоматически при запуске, вводить данный пользователя которому отправлять коины? Просто, если у тебя 10 токенов, то не очень удобно прописывать данные в ручную.

**Comment by PraKofnik** [comment]
Это сложно ва то если ты не программист

**Comment by Fomikus** [comment]
В батнике, в строке запуса js скрипта, команды можно ввести.
(Например:
@echo off
title Bot2
echo Launching bot . . .
node index.js -tsum 100000 -ti 600 -to VKID
echo Bot was forced to exit . . .
pause)
Создать для каждого свою папку со своим кфг.
Сделать запуск всех батников, через 1. PROFFIT

**Comment by longfest** [comment]
> В батнике, в строке запуса js скрипта, команды можно ввести.
> (Например:
> @echo off
> title Bot2
> echo Launching bot . . .
> node index.js -tsum 100000 -ti 600 -to VKID
> echo Bot was forced to exit . . .
> pause)
> Создать для каждого свою папку со своим кфг.
> Сделать запуск всех батников, через 1. PROFFIT

Всё сделал как ты написал, автоперевод включатся, но не включается tsum и ti. То есть деньги не переводятся.

**Comment by raywave** [comment]
ответ выше, мультиаккаунт введу после того, как его введет разраб vcoin.
