### ISSUE TITLE
Добавить фарм в баланс сообществ. 

### ISSUE THREAD

**Issue by UoSLondite** [cursedseal/VCoinX#59]
VKcoin сейчас является чем-то похожим на соревнование, среди популярных сообществ. Много людей оставляют включённым свой пк, чтобы фармить группе с нескольких аккаунтов. Чтобы майнить в сообщество, существуют ссылки с игрой от сообщества. Предлагаю ввести майнинг в кошелёк сообществ, тем самым привлекая тысячи людей к вашей разработке и улучшая ваш софт.

**Comment by 0WNNER** [comment]
да тоже очень хочу чтобы добавили фарм в сообщество

**Comment by raywave** [comment]
через ссылку можно, закрыто.
