### ISSUE TITLE
Не удаётся получить ссылку на приложение 

### ISSUE THREAD

**Issue by awskt** [cursedseal/VCoinX#6]
Указываю верный токен со всеми правами, запускаю,
_> API Error: Не удалось получить ссылку на приложение.

**Comment by raywave** [comment]
не могу сейчас проверить, попробуй указать токен по гайду из readme / сам получи ссылку по гайду из багосов и ставь бота через нее.

**Comment by awskt** [comment]
Получил токен через ссылку от багосов, все работает, пасиба
