### ISSUE TITLE
Предложение по улучшению 

### ISSUE THREAD

**Issue by whitemalina** [cursedseal/VCoinX#60]
Хотел бы чтобы вы добавили такую возможность как: сохранение переводов на Vkcoin в отдельный файл, чтобы можно было видеть кто переводил

**Comment by KEIIIA-HA-B3JIET** [comment]
Может быть добавить возможность создавать целые массивы с аккаунтами, чтобы не запускать для каждого отдельное приложение? (идея, как по мне, фуфел, но кто - то должен был это сказать)... Или  что - нибудь наподобии логов о переводах (хз, мб они уже есть).

**Comment by SHUM228** [comment]
Предлогаю такую штуку. При покупке нужно писать по несколько раз что бы купить много ускорителей, может сделать так, что бы при введении названия ускорения можно было бы написать кол-во шт пример: server_vk_3 . Так же при введении команды buy выводить информацию не только о стоимости но и максимальное кол-во , которое может купить пользователь.

**Comment by SHUM228** [comment]
ОО, придумал интересную штуку, но ее трудно будет создать. Смысл в том , что бы пользователь мог набрав определенную команду вывести строчку на свой экран. Она будет отображать кол-во койнов и обновляется каждую минуту или 15 секунд. Маленькая строчка (или окно можно сделать) можно будет перемещать из стороны в сторону . Ну или сделать еще по легче , это с помощью команды добавить значок в "Отображать скрытые значки". Если на него нажать, то он будет выводить кол-во койнов . Но это вам все не интересно)

**Comment by SHUM228** [comment]
Так же добавьте ДАТА ЦЕНТР!!!!

**Comment by SHUM228** [comment]
Так же добавьте возможность настройки автобай. Что бы было удобнее )))

**Comment by raywave** [comment]
по поводу первого сообщения - я подумаю, но вряд ли.

остальное - против.
