### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by WayPlay** [cursedseal/VCoinX#62]
Можно ли сделать мини меню, в котором будет показываться все функции, только уже кликабельные? Так же консоль оставить как debug окно.

**Comment by FirecYT** [comment]
Я как программист (ну или почти) могу сказать, что скорее всего невозможно сделать кликабельно в консоли. Только если через эмуляцию курсора, что уже довольно глупо.

**Comment by kyoukisu** [comment]
в консоли? нельзя? лол в линуксе гигантское множество программ из консоли могут отслеживать нажатия на визуальные кнопки в консоли. в крайнем случае сделать можно нажатия по цифрам (1 - первый пункт, 2 - второй и тд)

**Comment by raywave** [comment]
ха, против этой идеи.

если разраб vcoin введет, то придется согласиться.

создание интерфейса - привлечение еще большего внимания со стороны школьников, а следственно нужно еще больше фиксов делать, еще больше тех. поддержки, еще больше тупых вопросов.
