### ISSUE TITLE
Проблема с переводом "tran"

### ISSUE THREAD

**Issue by Slivondiy** [cursedseal/VCoinX#66]
Я отправил получателю коины, ввёл в консоль сумму койнов, id получателя, и написал YES.
Но койны ему так и не пришли, либо они сразу не приходят?

**Comment by LifeViwer** [comment]
Приходят моментально.
Вводить нужно только цифры.
Проверь точность ИД скопируй и глянь вк страницу та не так
и радуйся!

**Comment by Slivondiy** [comment]
Стоп, а например айди которой свой указан, а не стандартный от ВК? Что не будет действовать?

**Comment by LifeViwer** [comment]
> Стоп, а например айди которой свой указан, а не стандартный от ВК? Что не будет действовать?

Нет, толко цифры

**Comment by Slivondiy** [comment]
Хм... и куда тогда они ушли сейчас?

**Comment by Slivondiy** [comment]
Проблема с переводом, отправил по ID но коины не пришли!
![Безымянныйпропроп](https://user-images.githubusercontent.com/49315027/55668433-06330100-5873-11e9-9810-05e57b3eb1ff.png)

**Comment by Slivondiy** [comment]
> Проблема с переводом, отправил по ID но коины не пришли!
> ![Безымянныйпропроп](https://user-images.githubusercontent.com/49315027/55668433-06330100-5873-11e9-9810-05e57b3eb1ff.png)

Блин я случайно ID недописал, и куда теперь эти кионы ушли?

**Comment by skidunion** [comment]
Тому пользователю, которому ты их отправил (логично), перед отправкой ты подтвердил отправление, написав "yes"
