### ISSUE TITLE
Bot was forced to exit

### ISSUE THREAD

**Issue by ghost** [cursedseal/VCoinX#68]
После 3 часов работы, бот отказывается продолжать работу и выходит.

![123](https://user-images.githubusercontent.com/49320260/55654514-d3a9e980-581b-11e9-9932-cdb3db2393fb.jpg)

**Comment by Slivondiy** [comment]
Я лично перезапустил бота, и где 30мин подождал...

**Comment by raywave** [comment]
по поводу legacy в issues не отвечаю.

фиксы для него буду делать в последнюю очередь.
