### ISSUE TITLE
Предложение для улучшения скрипта

### ISSUE THREAD

**Issue by Ryaza5562** [cursedseal/VCoinX#69]
Добавьте параметр -beep, который будет издавать сигнал, когда вылетает какая-либо ошибка, дабы терять как можно меньше коинов)

**Comment by raywave** [comment]
позднее добавлю

**Comment by raywave** [comment]
хотя мб и не добавлю, обещать ничего не буду.

**Comment by Shlapich** [comment]
1 в автопереводе ошибки пишет(сам перевод работает)
2 было бы круто запилить умную прокачку аккаунтов(деньги со всех аккаунтов капают на самый слабый)

**Comment by raywave** [comment]
введено
