### ISSUE TITLE
Объясните не шарящему мне по поводу аргументов

### ISSUE THREAD

**Issue by xtvfrc123** [cursedseal/VCoinX#7]
Объясните пожалуйста как и куда прописывать аргументы, можете даже кинуть свой файл просто скажите где что поменять

**Comment by monkeswag** [comment]
https://github.com/cursedseal/VCoinX#использование-аргументов
Если ты про эти, то пкм по launch.bat, изменить, и после index.js через пробел пишешь аргументы.
Пример:
![image](https://user-images.githubusercontent.com/32573133/55548774-952b0680-5717-11e9-8c9c-6256655b3dbf.png)

**Comment by xtvfrc123** [comment]
> [https://github.com/cursedseal/VCoinX#использование-аргументов](https://github.com/cursedseal/VCoinX#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2)
> Если ты про эти, то пкм по launch.bat, изменить, и после index.js через пробел пишешь аргументы.
> Пример:
> ![image](https://user-images.githubusercontent.com/32573133/55548774-952b0680-5717-11e9-8c9c-6256655b3dbf.png)

Спасибо, буду пробывать

**Comment by raywave** [comment]
спасибо за ответ, закрыто.

**Comment by xtvfrc123** [comment]
> [https://github.com/cursedseal/VCoinX#использование-аргументов](https://github.com/cursedseal/VCoinX#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2)
> Если ты про эти, то пкм по launch.bat, изменить, и после index.js через пробел пишешь аргументы.
> Пример:
> ![image](https://user-images.githubusercontent.com/32573133/55548774-952b0680-5717-11e9-8c9c-6256655b3dbf.png)

дай пожалуйста ещё свой вк
