### ISSUE TITLE
Идея: ботнет

### ISSUE THREAD

**Issue by coldfeudal** [cursedseal/VCoinX#70]
Не знаю, как остальные, но лично я бы хотел в следующем обновлении увидеть функцию создания сети из ботов. Коротко о задаче сети: перекидывать койны таким образом, чтобы у всех ботов в сети был одинаковый доход в секунду, либо чтобы боты стремились добиться одинакового баланса. Перерасчитывать то, сколько должен переводить каждый бот, можно по времени, после каждой покупки или после каждого перевода

**Comment by LifeViwer** [comment]
Это очень сложно, логику очень хорошо нужно знать

**Comment by coldfeudal** [comment]
> Это очень сложно, логику очень хорошо нужно знать

Дел на полчаса, достаточно знать язык

**Comment by TeenKode** [comment]
Ну сделай, раз такой умный)
Я вот себе написал программку, которая из базы логин:пароль запускает ботов и автоматически размещает окна на рабочем столе + в заголовке окна показывает текущую сумму на каждом боте.
Для перекидывания денег нужен сложный алгоритм, одних сравнений балансов тут не хватит.

> > Это очень сложно, логику очень хорошо нужно знать
> 
> Дел на полчаса, достаточно знать язык

**Comment by raywave** [comment]
если разраб VCoin введет мультиаккаунт, то можно, а так нет, закрыто.

**Comment by coldfeudal** [comment]
> если разраб VCoin введет мультиаккаунт, то можно, а так нет, закрыто.

Допустим, запущен бот на трех акках. Дохода 5, 10 и 20 соответственно. Считаем среднюю арифметическую, выходит 11.3. Запуск цикла с итерациями = кол-ву ботов. В каждом считаем разность дохода, среднего дохода и переводов на акк в секунду. Если >0, то установка передачи по формуле доход-средний_доход.
