### ISSUE TITLE
Оказывается, автоперевод не работает должным образом

### ISSUE THREAD

**Issue by TeenKode** [cursedseal/VCoinX#73]
Параметры -tsum и -ti ни на что не влияют.
Вводишь 1000 каждые 5 минут - ничего не работает, как и с другими значениями. По дефолту только он переводит, как только баланс достигает 30к.
Ну в последний день и дефолт перестал работать.

**Comment by IdeaManM2** [comment]
Проверенный способ: Переустанови.

**Comment by TeenKode** [comment]
@IdeaManM2 Ну ясен пень, перезапуск, конечно же, помогает, и они тут же бросаются переводить все)

**Comment by raywave** [comment]
В легаси версии некорректно все сделано, позднее сделаю патч.
