### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by Dampir93** [cursedseal/VCoinX#74]
При запуске вылетает это
![2019-04-06_011201](https://user-images.githubusercontent.com/8216058/55660924-11e9dd80-5809-11e9-8479-a09041ca6da0.png)
Я не разбираюсь в node js , может что-то не так запускаю(

**Comment by TeenKode** [comment]
@Dampir93 Тебе надо установить модули node js. 
В папке с ботом должна быть папка node_modules. Запусти 1. Install.bat
А для установки модулей не хватает файла package.json

**Comment by raywave** [comment]
Попробуй отключить защитник Windows, это проблема самого nodejs и системы, не приложения.
