### ISSUE TITLE
Предложение по улучшению. Алгоритм закупки улучшений.

### ISSUE THREAD

**Issue by Out0fTheFire** [cursedseal/VCoinX#76]
При покупке любого улучшения его стоимость увеличивается на 30% от первого значения.
Грубо говоря квантовый компьютер стоит 10 000 и дает +0.5, но мы можем купить несколько серверов вк за 9 000 и получить те же +0.5.
На данный момент бот скупает сразу то улучшение на которое ему хватает средств

**Comment by raywave** [comment]
Введена смарт-покупка.
