### ISSUE TITLE
group id

### ISSUE THREAD

**Issue by monkeswag** [cursedseal/VCoinX#8]
Как майнить через сообщество?
Пробовал в ссылку добавить "vk_group_id=", но выдаёт ошибку.

on Message:
 BROKEN
[04.04.2019 20:34:28]: onBrokenEvent
[04.04.2019 20:34:28]: onOffline

**Comment by raywave** [comment]
в ссылке он уже есть, как и буду дома, доделаю readme.

**Comment by YamkaFox** [comment]
Тобиш майнинг на вашу группу?
