### ISSUE TITLE
smartBuy

### ISSUE THREAD

**Issue by de-don** [cursedseal/VCoinX#80]
Чет не работает автопокупка.

запускаю через 
`node index.js -smartBuy`

И он просто фармит.

**Comment by Fomikus** [comment]
Просто введи в окошко smartbuy - заработает

**Comment by de-don** [comment]
При работе скрипта? нет, не заработало

**Comment by de-don** [comment]
Пришлось ручками поправить дефолтные настройки в `index.js` в линии 52

**Comment by lokkeders** [comment]
скажи, что нужно исправить?

**Comment by lokkeders** [comment]
у меня тоже ничего не робит

**Comment by de-don** [comment]
Я же написал https://github.com/cursedseal/VCoinX/issues/80#issuecomment-480477511
изменить `smartBuy = false,` на `smartBuy = true,`

**Comment by raywave** [comment]
в параметры запуска еще не добавил, сори.

**Comment by de-don** [comment]
Кек, зачем тогда было добавлять в описание)
