### ISSUE TITLE
проблема с запуском

### ISSUE THREAD

**Issue by ghost** [cursedseal/VCoinX#82]
![image](https://user-images.githubusercontent.com/45308130/55665676-93169400-584c-11e9-811c-ce2b38b10881.png)
![image](https://user-images.githubusercontent.com/45308130/55665703-d40ea880-584c-11e9-9f09-830026f5e855.png)
node 13.11.0 я хз чё делать если честно

**Comment by zikle** [comment]
Попробуй конфиг дефольный поставить 
```
module.exports = {
    VK_TOKEN: "",
    DONEURL: ""
};
```

**Comment by raywave** [comment]
запятая после вктокена не указана, либо удали дон юрл.

**Comment by zikle** [comment]
Или скинь конфиг который сейчас у тебя

**Comment by ghost** [comment]
ДА В КАКОМ СМЫСЛЕ ОНО СРАБОТАЛО С ЗАПЯТОЙ

там раньше и была запятая..... какого
