### ISSUE TITLE
Не покупаются автоматом итемы

### ISSUE THREAD

**Issue by xtvfrc123** [cursedseal/VCoinX#9]
Вроде получилось зайти с аргументами, но вот не задача не работает автопокупка, прописывал через конкретный итем на датацентр, в итоге он его не покупает. Подскажите пожалуйста
![image](https://user-images.githubusercontent.com/49272337/55552174-de268f00-5706-11e9-8aff-cdd9c791cc57.png)
![image](https://user-images.githubusercontent.com/49272337/55552187-e979ba80-5706-11e9-9a7a-dfaf078232d1.png) токенов хватает а он не покупает, также расскажите как писать сюда ещё итемы помимо этого через пробел или ещё как то, и можно ли включить что бы пкупал всё подряд. Спасибо

**Comment by raywave** [comment]
автопокупка включена впринципе?

**Comment by xtvfrc123** [comment]
а как это сделать?)

**Comment by raywave** [comment]
ибо на скрине я вижу только установку предмета без включения его как такового

**Comment by xtvfrc123** [comment]
![image](https://user-images.githubusercontent.com/49272337/55552297-39f11800-5707-11e9-825b-e2d6ea5ac123.png)
так нужно ?

**Comment by xtvfrc123** [comment]
или надо может true дописать ?

**Comment by xtvfrc123** [comment]
> ибо на скрине я вижу только установку предмета без включения его как такового

![image](https://user-images.githubusercontent.com/49272337/55552554-dddac380-5707-11e9-9667-ff2b969ec05f.png)
ну так он тоже не покупает

**Comment by xtvfrc123** [comment]
> ибо на скрине я вижу только установку предмета без включения его как такового

5 минут с включенным и также ничего, коинов хватает

**Comment by AutismGaming228** [comment]
Подтверждаю, автопокупка не работает
Токенов достаточно но ничего само не покупается

**Comment by banysk** [comment]
Кто может объяснить, как прописать команды для автоперевода средств на другой аккаунт?

**Comment by raywave** [comment]
Спасибо за баг, по идее исправил.
