### ISSUE TITLE
предложения по улучшению

### ISSUE THREAD

**Issue by oleganno228** [cursedseal/VCoinX#93]
1. сделать счетчик процентов по улучшениям (подсчитывает, какое улучшение дешевле по сравнению с остальными и будет профитнее)
2. сделать фарм для групп. Например вводишь команду, появляется список групп и выбираешь какую либо, чтобы ты фармил за неё.

**Comment by Allespro** [comment]
Ещё одно предложение, создай беседу в телеге, для истинных ононимов

**Comment by Ryaza5562** [comment]
Сделайте команду, чтобы выводило твой id в консоли

**Comment by rev0ns** [comment]
Добавьте функцию чтобы можно было за группы играть

**Comment by raywave** [comment]
1. нет
2. нет
3. нет
4. нет
5. нет

**Comment by Allespro** [comment]
> Сделайте команду, чтобы выводило твой id в консоли

Это уже есть, имя окна посмотри
