### ISSUE TITLE
Просьба сделать этот репозиторий не форком 

### ISSUE THREAD

**Issue by mlv-dev** [cursedseal/VCoinX#96]
Я опишу две причины на это:
1. Как я понял, это самостоятельный репозиторий, который не планируется объединять с VCoinX, поэтому механика Pull Request'а тут не нужна.
2. Так как это самостоятельный репозиторий, люди (в том числе и я) захотят в него контрибьютить. И не смогут.
Механика Pull Request'а: fork -> host repository.
И что бы люди смогли сделать запрос сюда им нужно что бы это репозиторий был сам по себе, а не форком (что бы они смогли сделать форк этого и предложить изменения).

**Comment by raywave** [comment]
pull request тут работает.

обьеденять с vcoin не планируется, ибо разные авторы и к согласию не придем никогда, однако будучи форком я могу пиздить у него апдейты и мне это нравится.
