### ISSUE TITLE
Опечатка в сообщении об успешном получении

### ISSUE THREAD

**Issue by Artyom152** [cursedseal/VCoinX#98]
Опечатка в слове **пользОватель**
![image](https://user-images.githubusercontent.com/32091688/55671708-6e95d880-589b-11e9-96c8-32c5f7562f75.png)

**Comment by Artyom152** [comment]
+1
![image](https://user-images.githubusercontent.com/32091688/55671978-4bb8f380-589e-11e9-8399-bc30929f4215.png)

**Comment by raywave** [comment]
пофикшу в некст апдейте, спасибо
